
 <p class='ing'> coffee </p>
 <p class='ing'> orange juice </p>
 <p class='ing'> tea </p>
 <p class='ing'> green tea </p>
 <p class='ing'> apple juice </p>
 <p class='ing'> tomato juice </p>
 <p class='ing'> coke </p>
 <p class='ing'> chocolate milk </p>
 <p class='ing'> pineapple juice </p>
 <p class='ing'> lemonade </p>
 <p class='ing'> cranberry juice </p>
 <p class='ing'> espresso </p>
 <p class='ing'> fruit juice </p>
 <p class='ing'> ginger ale </p>
 <p class='ing'> club soda </p>
 <p class='ing'> sprite </p>
 <p class='ing'> kool aid </p>
 <p class='ing'> grenadine </p>
 <p class='ing'> margarita mix </p>
 <p class='ing'> cherry juice </p>
 <p class='ing'> pepsi </p>
 <p class='ing'> mountain dew </p>